name: bt_hydra_byo
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7.5
  - pandas=1.0.5
  - pip=20.0.2
  - pip:
    - backtrader==1.9.75.123
    - requests==2.24.0
    - hydra-core==0.11.3  
    - omegaconf==1.4.1
    - backtrader-plotting==1.1.0
    - bayesian-optimization==1.2.0

    
  

